# Change these first
owner: benfoster04 # Your GitHub username
repo: status # Your GitHub repository name

# Add your sites here
sites:
  - name: Canary Page
    url: https://canary.benfoster.dev
  - name: Main Site
    url: https://benfoster.dev
  - name: Script API
    url: https://benfoster.dev/script/api
  - name: Code Page
    url: https://benfoster.dev/code

assignees:
  - benfoster04

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.benfoster.dev
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/benfoster04/status/master/logo_white.png
  name: Ben Foster Development
  introTitle: Ben Foster Development Status Page
  introMessage: Personal status page detailing the availability of publicly available services provided by me
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Homepage
      href: https://benfoster.dev

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
