# Change these first
owner: benfoster04 # Your GitHub username
repo: status # Your GitHub repository name

# Add your sites here
sites:
  - name: Canary Page
    url: https://canary.benfoster.dev
  - name: Main Site
    url: https://benfoster.dev
  - name: Script API
    url: https://benfoster.dev/script/test
  - name: Code Page
    url: https://code.benfoster.dev

assignees:
  - benfoster04

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.benfoster.dev
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  # logoUrl: https://raw.githubusercontent.com/benfoster04/status/master/logo_white.png
  name: "Ben Foster"
  introTitle: Ben Foster Development Status Page
  introMessage: Personal status page detailing the availability of publicly available services provided by me
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER
    - title: Homepage
      href: https://benfoster.dev
  css: "h4.logo{font-size:18pt;font-family:'Pacifico',cursive;word-spacing:-3px}h4.logo::before{content:'<';font-size:16pt}h4.logo::after{content:'/>';font-size:16pt}body{color:#fff;background:#000}article{background-color:#111}main.container > section:first-of-type > article.degraded{background:#111;border: 0.2rem solid #f39c12}main.container > section:first-of-type > article.down{background-color:#111;border: 0.2rem solid #e74c3c}main.container > article.good{background-color:#000;border: 2px solid #00bd00;color:#fff}section > article > h4 > img{display:none}div#sapper > nav{padding:0;background-color:#111}"
  links:
    #- rel: stylesheet
    #  href: https://raw.githubusercontent.com/benfoster04/status/master/style.css
    - rel: stylesheet
      href: https://fonts.googleapis.com/css2?family=Pacifico
      
i18n:
  footer: Copyright Ben Foster Development 2021 - All Rights Reserved.
  up: Online
  down: Offline
  degraded: Partial
  incidentFixed: Rectified
  incidentBack: ← Return
  pastIncidents: Incident History

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
